/* apaylibClientLib.c
   Generated by gSOAP 2.7.7 from apaylib.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "apaylibC.c"
#include "apaylibClient.c"

/* End of apaylibClientLib.c */
