/* apaylibClient.c
   Generated by gSOAP 2.7.7 from apaylib.h
   Copyright (C) 2000-2005, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "apaylibH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) apaylibClient.c ver 2.7.7 2015-07-15 13:57:21 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_baidu__scanpay(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct baidu__scanPayReq *scanPayReq, struct baidu__scanpayResponse *_param_1)
{	struct baidu__scanpay soap_tmp_baidu__scanpay;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/baiduservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_baidu__scanpay.scanPayReq = scanPayReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_baidu__scanpay(soap, &soap_tmp_baidu__scanpay);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_baidu__scanpay(soap, &soap_tmp_baidu__scanpay, "baidu:scanpay", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_baidu__scanpay(soap, &soap_tmp_baidu__scanpay, "baidu:scanpay", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_baidu__scanpayResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_baidu__scanpayResponse(soap, _param_1, "baidu:scanpayResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_baidu__refund(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct baidu__refundReq *refundReq, struct baidu__refundResponse *_param_2)
{	struct baidu__refund soap_tmp_baidu__refund;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/baiduservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_baidu__refund.refundReq = refundReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_baidu__refund(soap, &soap_tmp_baidu__refund);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_baidu__refund(soap, &soap_tmp_baidu__refund, "baidu:refund", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_baidu__refund(soap, &soap_tmp_baidu__refund, "baidu:refund", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_baidu__refundResponse(soap, _param_2);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_baidu__refundResponse(soap, _param_2, "baidu:refundResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_baidu__cancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct baidu__cancelReq *cancelReq, struct baidu__cancelResponse *_param_3)
{	struct baidu__cancel soap_tmp_baidu__cancel;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/baiduservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_baidu__cancel.cancelReq = cancelReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_baidu__cancel(soap, &soap_tmp_baidu__cancel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_baidu__cancel(soap, &soap_tmp_baidu__cancel, "baidu:cancel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_baidu__cancel(soap, &soap_tmp_baidu__cancel, "baidu:cancel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_baidu__cancelResponse(soap, _param_3);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_baidu__cancelResponse(soap, _param_3, "baidu:cancelResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_baidu__orderquery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct baidu__orderQueryReq *orderQueryReq, struct baidu__orderqueryResponse *_param_4)
{	struct baidu__orderquery soap_tmp_baidu__orderquery;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/baiduservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_baidu__orderquery.orderQueryReq = orderQueryReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_baidu__orderquery(soap, &soap_tmp_baidu__orderquery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_baidu__orderquery(soap, &soap_tmp_baidu__orderquery, "baidu:orderquery", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_baidu__orderquery(soap, &soap_tmp_baidu__orderquery, "baidu:orderquery", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_baidu__orderqueryResponse(soap, _param_4);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_baidu__orderqueryResponse(soap, _param_4, "baidu:orderqueryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_baidu__reversal(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct baidu__reversalReq *reversalReq, struct baidu__reversalResponse *_param_5)
{	struct baidu__reversal soap_tmp_baidu__reversal;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/baiduservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_baidu__reversal.reversalReq = reversalReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_baidu__reversal(soap, &soap_tmp_baidu__reversal);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_baidu__reversal(soap, &soap_tmp_baidu__reversal, "baidu:reversal", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_baidu__reversal(soap, &soap_tmp_baidu__reversal, "baidu:reversal", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_baidu__reversalResponse(soap, _param_5);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_baidu__reversalResponse(soap, _param_5, "baidu:reversalResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponWithdraw(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__withdrawReq *WithdrawReq, struct coupon__couponWithdrawResponse *_param_6)
{	struct coupon__couponWithdraw soap_tmp_coupon__couponWithdraw;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponWithdraw.WithdrawReq = WithdrawReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponWithdraw(soap, &soap_tmp_coupon__couponWithdraw);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponWithdraw(soap, &soap_tmp_coupon__couponWithdraw, "coupon:couponWithdraw", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponWithdraw(soap, &soap_tmp_coupon__couponWithdraw, "coupon:couponWithdraw", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponWithdrawResponse(soap, _param_6);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponWithdrawResponse(soap, _param_6, "coupon:couponWithdrawResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__chargeBack(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__backChargeReq *BackChargeReq, struct coupon__chargeBackResponse *_param_7)
{	struct coupon__chargeBack soap_tmp_coupon__chargeBack;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__chargeBack.BackChargeReq = BackChargeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__chargeBack(soap, &soap_tmp_coupon__chargeBack);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__chargeBack(soap, &soap_tmp_coupon__chargeBack, "coupon:chargeBack", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__chargeBack(soap, &soap_tmp_coupon__chargeBack, "coupon:chargeBack", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__chargeBackResponse(soap, _param_7);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__chargeBackResponse(soap, _param_7, "coupon:chargeBackResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponMobileExchange(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__couponMobileExchangeReq *CouponMobileExchangeReq, struct coupon__couponMobileExchangeResponse *_param_8)
{	struct coupon__couponMobileExchange soap_tmp_coupon__couponMobileExchange;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponMobileExchange.CouponMobileExchangeReq = CouponMobileExchangeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponMobileExchange(soap, &soap_tmp_coupon__couponMobileExchange);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponMobileExchange(soap, &soap_tmp_coupon__couponMobileExchange, "coupon:couponMobileExchange", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponMobileExchange(soap, &soap_tmp_coupon__couponMobileExchange, "coupon:couponMobileExchange", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponMobileExchangeResponse(soap, _param_8);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponMobileExchangeResponse(soap, _param_8, "coupon:couponMobileExchangeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponSingle(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__couponSingleReq *CouponSingleReq, struct coupon__couponSingleResponse *_param_9)
{	struct coupon__couponSingle soap_tmp_coupon__couponSingle;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponSingle.CouponSingleReq = CouponSingleReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponSingle(soap, &soap_tmp_coupon__couponSingle);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponSingle(soap, &soap_tmp_coupon__couponSingle, "coupon:couponSingle", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponSingle(soap, &soap_tmp_coupon__couponSingle, "coupon:couponSingle", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponSingleResponse(soap, _param_9);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponSingleResponse(soap, _param_9, "coupon:couponSingleResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponPanExchange(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__couponPanExchangeReq *CouponPanExchangeReq, struct coupon__couponPanExchangeResponse *_param_10)
{	struct coupon__couponPanExchange soap_tmp_coupon__couponPanExchange;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponPanExchange.CouponPanExchangeReq = CouponPanExchangeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponPanExchange(soap, &soap_tmp_coupon__couponPanExchange);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponPanExchange(soap, &soap_tmp_coupon__couponPanExchange, "coupon:couponPanExchange", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponPanExchange(soap, &soap_tmp_coupon__couponPanExchange, "coupon:couponPanExchange", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponPanExchangeResponse(soap, _param_10);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponPanExchangeResponse(soap, _param_10, "coupon:couponPanExchangeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponSearchByMobile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__couponSerachByMobileReq *CouponSearchByMobileReq, struct coupon__couponSearchByMobileResponse *_param_11)
{	struct coupon__couponSearchByMobile soap_tmp_coupon__couponSearchByMobile;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponSearchByMobile.CouponSearchByMobileReq = CouponSearchByMobileReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponSearchByMobile(soap, &soap_tmp_coupon__couponSearchByMobile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponSearchByMobile(soap, &soap_tmp_coupon__couponSearchByMobile, "coupon:couponSearchByMobile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponSearchByMobile(soap, &soap_tmp_coupon__couponSearchByMobile, "coupon:couponSearchByMobile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponSearchByMobileResponse(soap, _param_11);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponSearchByMobileResponse(soap, _param_11, "coupon:couponSearchByMobileResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponCodeExchange(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__couponIdExchangeReq *CouponIdExchangeReq, struct coupon__couponCodeExchangeResponse *_param_12)
{	struct coupon__couponCodeExchange soap_tmp_coupon__couponCodeExchange;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponCodeExchange.CouponIdExchangeReq = CouponIdExchangeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponCodeExchange(soap, &soap_tmp_coupon__couponCodeExchange);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponCodeExchange(soap, &soap_tmp_coupon__couponCodeExchange, "coupon:couponCodeExchange", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponCodeExchange(soap, &soap_tmp_coupon__couponCodeExchange, "coupon:couponCodeExchange", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponCodeExchangeResponse(soap, _param_12);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponCodeExchangeResponse(soap, _param_12, "coupon:couponCodeExchangeResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__couponSearchByPan(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__couponSerachByPanReq *CouponSearchByPanReq, struct coupon__couponSearchByPanResponse *_param_13)
{	struct coupon__couponSearchByPan soap_tmp_coupon__couponSearchByPan;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__couponSearchByPan.CouponSearchByPanReq = CouponSearchByPanReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__couponSearchByPan(soap, &soap_tmp_coupon__couponSearchByPan);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__couponSearchByPan(soap, &soap_tmp_coupon__couponSearchByPan, "coupon:couponSearchByPan", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__couponSearchByPan(soap, &soap_tmp_coupon__couponSearchByPan, "coupon:couponSearchByPan", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__couponSearchByPanResponse(soap, _param_13);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__couponSearchByPanResponse(soap, _param_13, "coupon:couponSearchByPanResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_coupon__sgin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct coupon__sginReq *SginReq, struct coupon__sginResponse *_param_14)
{	struct coupon__sgin soap_tmp_coupon__sgin;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/service";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_coupon__sgin.SginReq = SginReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_coupon__sgin(soap, &soap_tmp_coupon__sgin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_coupon__sgin(soap, &soap_tmp_coupon__sgin, "coupon:sgin", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_coupon__sgin(soap, &soap_tmp_coupon__sgin, "coupon:sgin", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_coupon__sginResponse(soap, _param_14);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_coupon__sginResponse(soap, _param_14, "coupon:sginResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wechat__cancel(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wechat__cancelReq *cancelReq, struct wechat__cancelResponse *_param_15)
{	struct wechat__cancel soap_tmp_wechat__cancel;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/wxservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_wechat__cancel.cancelReq = cancelReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_wechat__cancel(soap, &soap_tmp_wechat__cancel);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_wechat__cancel(soap, &soap_tmp_wechat__cancel, "wechat:cancel", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_wechat__cancel(soap, &soap_tmp_wechat__cancel, "wechat:cancel", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_wechat__cancelResponse(soap, _param_15);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_wechat__cancelResponse(soap, _param_15, "wechat:cancelResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wechat__reversal(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wechat__reversalReq *reversalReq, struct wechat__reversalResponse *_param_16)
{	struct wechat__reversal soap_tmp_wechat__reversal;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/wxservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_wechat__reversal.reversalReq = reversalReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_wechat__reversal(soap, &soap_tmp_wechat__reversal);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_wechat__reversal(soap, &soap_tmp_wechat__reversal, "wechat:reversal", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_wechat__reversal(soap, &soap_tmp_wechat__reversal, "wechat:reversal", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_wechat__reversalResponse(soap, _param_16);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_wechat__reversalResponse(soap, _param_16, "wechat:reversalResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wechat__unifiedorder(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wechat__unifiedorderReq *unifiedorderReq, struct wechat__unifiedorderResponse *_param_17)
{	struct wechat__unifiedorder soap_tmp_wechat__unifiedorder;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/wxservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_wechat__unifiedorder.unifiedorderReq = unifiedorderReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_wechat__unifiedorder(soap, &soap_tmp_wechat__unifiedorder);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_wechat__unifiedorder(soap, &soap_tmp_wechat__unifiedorder, "wechat:unifiedorder", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_wechat__unifiedorder(soap, &soap_tmp_wechat__unifiedorder, "wechat:unifiedorder", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_wechat__unifiedorderResponse(soap, _param_17);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_wechat__unifiedorderResponse(soap, _param_17, "wechat:unifiedorderResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wechat__micripay(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wechat__micropayReq *micropayReq, struct wechat__micripayResponse *_param_18)
{	struct wechat__micripay soap_tmp_wechat__micripay;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/wxservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_wechat__micripay.micropayReq = micropayReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_wechat__micripay(soap, &soap_tmp_wechat__micripay);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_wechat__micripay(soap, &soap_tmp_wechat__micripay, "wechat:micripay", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_wechat__micripay(soap, &soap_tmp_wechat__micripay, "wechat:micripay", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_wechat__micripayResponse(soap, _param_18);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_wechat__micripayResponse(soap, _param_18, "wechat:micripayResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wechat__refund(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wechat__refundReq *refundReq, struct wechat__refundResponse *_param_19)
{	struct wechat__refund soap_tmp_wechat__refund;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/wxservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_wechat__refund.refundReq = refundReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_wechat__refund(soap, &soap_tmp_wechat__refund);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_wechat__refund(soap, &soap_tmp_wechat__refund, "wechat:refund", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_wechat__refund(soap, &soap_tmp_wechat__refund, "wechat:refund", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_wechat__refundResponse(soap, _param_19);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_wechat__refundResponse(soap, _param_19, "wechat:refundResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_wechat__orderquery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct wechat__orderQueryReq *orderQueryReq, struct wechat__orderqueryResponse *_param_20)
{	struct wechat__orderquery soap_tmp_wechat__orderquery;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.16.32:8800/apay-ws/services/pos/wxservice";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp_wechat__orderquery.orderQueryReq = orderQueryReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_wechat__orderquery(soap, &soap_tmp_wechat__orderquery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_wechat__orderquery(soap, &soap_tmp_wechat__orderquery, "wechat:orderquery", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_wechat__orderquery(soap, &soap_tmp_wechat__orderquery, "wechat:orderquery", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_wechat__orderqueryResponse(soap, _param_20);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_wechat__orderqueryResponse(soap, _param_20, "wechat:orderqueryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of apaylibClient.c */
