#ifndef _DICTION_ADC_PUBLIC_H_
#define _DICTION_ADC_PUBLIC_H_
#define  PROCESSCODE            1        /* 处理码                       */
#define  RESPONSE               2        /* 响应代码                     */
#define  RETMSG                 3        /* 响应信息                     */
#define  MERCHANTID             4        /* 商户号                       */
#define  TERMID                 5        /* 终端号                       */
#define  MASTERKEY              6        /* 主密钥                       */
#define  MASTERKEYINDEX         7        /* 主密钥索引                   */
#define  MACKEY                 8        /* MACKEY                       */
#define  PINKEY                 9        /* PINKEY                       */
#define  MACCHECK               10       /* MAC校验位                    */
#define  PINCHECK               11       /* PIN校验位                    */
#define  TXDATE                 12       /* 平台账务日期                 */
#define  TXTIME                 13       /* 交易时间                     */
#define  OPERID                 14       /* 操作员号                     */
#define  SERIAL                 15       /* 平台流水号                   */
#define  BATCHNO                16       /* 批次号                       */
#define  CHANNELID              17       /* 渠道号                       */
#define  ALLKEY                 18       /* 密钥字段                     */
#define  PARAM                  19       /* 参数结构                     */
#define  PARAMVER               20       /* 参数版本号                   */
#define  PROGRAMVER             21       /* 程序版本号                   */
#define  ACCTNO                 22       /* 交易主帐号                   */
#define  PERIOD                 23       /* 有效期                       */
#define  TXAMT                  24       /* 交易金额                     */
#define  TXNUM                  25       /* 交易次数                     */
#define  CHDATE                 26       /* 渠道日期                     */
#define  CHTIME                 27       /* 渠道时间                     */
#define  EXRESPONSE             28       /* 外联响应码                   */
#define  EXRETMSG               29       /* 外联响应信息                 */
#define  PROCODE                30       /* 产品代码                     */
#define  UNITCODE               31       /* 单位编码                     */
#define  CHTXCODE               32       /* 渠道处理码                   */
#define  CHSERIAL               33       /* 渠道流水                     */
#define  HOTXCODE               34       /* 主机处理码                   */
#define  HOSERIAL               35       /* 主机流水                     */
#define  STATUS                 36       /* 状态                         */
#define  HORESPONSE             37       /* 主机响应码                   */
#define  HORETMSG               38       /* 主机响应信息                 */
#define  EXSERIAL               39       /* 外联流水号                   */
#define  EXTXCODE               40       /* 外联交易代码                 */
#define  CHRESPONSE             41       /* 渠道响应码                   */
#define  CHRETMSG               42       /* 渠道响应信息                 */
#define  ACCTTYPE               43       /* 主帐号类型                   */
#define  BALANCE                44       /* 主帐号余额                   */
#define  OLDSERIAL              45       /* 原交易流水                   */
#define  OLDDATE                46       /* 原交易日期                   */
#define  OLDPROCESSCODE         47       /* 原渠道交易处理码             */
#define  BALNUM                 48       /* 剩余次数                     */
#define  MSGID                  49       /* 消息类型                     */
#endif

