#ifndef __PUBLIC_STRUCTURE_H__
#define __PUBLIC_STRUCTURE_H__

EXEC SQL BEGIN DECLARE SECTION;
typedef struct _visa_info
{
  char      m_sProCode[4];
  char      m_sUnitCode[7];
  char      m_sProName[21];
  char      m_sVisaName[33];
  char      m_sCityCode[21];
  double    m_fPayLimit;  
  char      m_sInteAcctType[2];
  char      m_sInteAcct[33];
  char      m_sLateFeeAcctType[2];
  char      m_sLateFeeAcct[33];
  char      m_sVisaOrg[21];  
  char      m_sVisaTeller[21];
  char      m_sVisaDate[11];
  int       m_nCurBatch;
  char      m_sWorkDate[9];
  int       m_nLastBatch;
  char      m_sChkFlag[2];
  char      m_sStatus[2];
  char      m_sNote[65];
  char      m_sDAC[17];
}VisaInfo;
typedef struct _visa_info_ind
{
  short      m_nProCode;
  short      m_nUnitCode;
  short      m_nProName;
  short      m_nVisaName;
  short      m_nCityCode;
  short      m_nPayLimit;  
  short      m_nInteAcctType;
  short      m_nInteAcct;
  short      m_nLateFeeAcctType;
  short      m_nLateFeeAcct;
  short      m_nVisaOrg;  
  short      m_nVisaTeller;
  short      m_nVisaDate;
  short      m_nCurBatch;
  short      m_nWorkDate;
  short      m_nLastBatch;
  short      m_nChkFlag;
  short      m_nStatus;
  short      m_nNote;
  short      m_nDAC;
}VisaInfoInd;

typedef struct _cmd_result
{
   int       m_nPtSerial;
   char      m_sPtDate[9]; 
   char      m_sProCode[11];
   char      m_sProInfo[65];
   char      m_sStartDate[9]; 
   char      m_sStartTime[7];
   char      m_sEndDate[9]; 
   char      m_sEndTime[7];
   char      m_sCmdStatus[2]; 
   char      m_sNote[101];  
   char      m_sOper[21];
} CmdResult;
typedef struct _cmd_result_ind
{
   short     m_nPtSerial;
   short     m_nPtDate; 
   short     m_nProCode;
   short     m_nProInfo;
   short     m_nStartDate; 
   short     m_nStartTime;
   short     m_nEndDate; 
   short     m_nEndTime;
   short     m_nCmdStatus; 
   short     m_nNote;  
   short     m_nOper;
} CmdResultInd;

typedef struct _sys_info
{
  char       m_sCode[21];
  int        m_nNodeId;
  char       m_sNextWorkDate[9];
  char       m_sWorkDate[9];
  char       m_sLastWorkDate[9];
  int        m_nCurSerial;
  int        m_nCurBatch;
  int        m_nLastBatch;
  char       m_sAuthKey[33];
  char       m_sStatus[2];
  char       m_sTxOrg[21];
  char       m_sTxKind[3];
  char       m_sTermId[21];
  char       m_sTeller[21];
  char       m_sAuthTeller[21];
  char       m_sDac[17];
}SysInfo;

typedef struct _sys_info_ind
{
  short      m_nCode;
  short      m_nNodeId;
  short      m_nNextWorkDate;
  short      m_nWorkDate;
  short      m_nLastWorkDate;
  short      m_nCurSerial;
  short      m_nCurBatch;
  short      m_nLastBatch;
  short      m_nAuthKey;
  short      m_nStatus;
  short      m_nTxOrg;
  short      m_nTxKind;
  short      m_nTermId;
  short      m_nTeller;
  short      m_nAuthTeller;
  short      m_nDac;
}SysInfoInd;

typedef struct _ch_code
{
   int          m_nCode;
   char         m_sName[32+1];
   char         m_sAreaCode[10+1];
   char         m_sCityCode[10+1];
   double       m_fPayLimit;
   char         m_sTxTeller[20+1];
   char         m_sTxOrg[20+1];
   char         m_sStatus[1+1];
   char         m_sAppId[20+1];
   char         m_sNote[64+1];
   char         m_sDac[16+1];
}ChCode;
typedef struct _ch_code_ind
{
   short        m_nCode;
   short        m_nName;
   short        m_nAreaCode;
   short        m_nCityCode;
   short        m_nPayLimit;
   short        m_nTxTeller;
   short        m_nTxOrg;
   short        m_nStatus;
   short        m_nAppId;
   short        m_nNote;
   short        m_nDac;
}ChCodeInd;

typedef struct _tx_detail
{
    int         m_nPtSerial;
    char        m_sPtDate[8+1];
    int         m_nBatchNo;
    int         m_nInvoice;
    char        m_sProduct[3+1];
    char        m_sUnitCode[6+1];
    char        m_sMerchantId[15+1];
    char        m_sTerminalId[8+1];
    char        m_sSubMerchantId[15+1];
    char        m_sSeatId[20+1];
    char        m_sMccCode[4+1];
    int         m_nChCode;
    char        m_sChMsgid[5+1];
    char        m_sChTxCode[12+1];
    char        m_sChDate[8+1];
    char        m_sChTime[6+1];
    char        m_sChSerial[8+1];
    char        m_sChBatch[8+1];
    char        m_sChRetCode[12+1];
    char        m_sChRetMsg[100+1];
    char        m_sSysDate[8+1];
    char        m_sSysTime[6+1];
    char        m_sHoTxCode[12+1];
    char        m_sHoSerial[12+1];
    char        m_sHoRetCode[12+1];
    char        m_sHoRetMsg[100+1];
    char        m_sExTxCode[12+1];
    char        m_sExSerial[12+1];
    char        m_sExRetCode[12+1];
    char        m_sExRetMsg[100+1];
    char        m_sAuthNo[12+1];
    char        m_sRefNum[20+1];
    char        m_sSettleDate[8+1];
    char        m_sSettleTime[6+1];
    char        m_sTxTeller[15+1];
    char        m_sTxOrg[20+1];
    int         m_nErrHostId;
    double      m_fTxAmt;
    double      m_fAddAmt;
    double      m_fLateFee;
    double      m_fChkAmt;
    int         m_nTxNum;
    int         m_nChkNum;
    int         m_nTxIntegral;
    int         m_nChkIntegral;
    int         m_nStagingNum;
    char        m_sStagingCode[15+1];
    char        m_sReceiptBank[30+1];
    char        m_sIssureBank[30+1];
    char        m_sCupFlag[6+1];
    char        m_sPayerCardName[20+1];
    char        m_sPayerAcctType[6+1];
    char        m_sPayerAcct[32+1];
    double      m_fPayerBal;
    int         m_nPayerBalNum;
    char        m_sPayeeCardName[20+1];
    char        m_sPayeeAcctType[6+1];
    char        m_sPayeeAcct[32+1];
    double      m_fPayeeBal;
    int         m_nPayeeBalNum;
    char        m_sPeriod[4+1];
    char        m_sCustomerId[20+1];
    char        m_sOrderId[30+1];
    char        m_sChgDate[8+1];
    char        m_sChgTime[6+1];
    char        m_sAuthTeller[15+1];
    char        m_sChgTeller[15+1];
    char        m_sStatus[1+1];
    char        m_sAcctChkFlag[1+1];
    char        m_sOldStatus[1+1];
    int         m_nOldPtSerial;
    char        m_sOldPtDate[8+1];
    char        m_sMac[16+1];
    char        m_sNote[100+1];
    char        m_sDac[16+1];
}T_TxDetail;
typedef struct _tx_detail_ind
{
    short       m_nPtSerial;
    short       m_nPtDate;
    short       m_nBatchNo;
    short       m_nInvoice;
    short       m_nProduct;
    short       m_nUnitCode;
    short       m_nMerchantId;
    short       m_nTerminalId;
    short       m_nSubMerchantId;
    short       m_nSeatId;
    short       m_nMccCode;
    short       m_nChCode;
    short       m_nChMsgid;
    short       m_nChTxCode;
    short       m_nChDate;
    short       m_nChTime;
    short       m_nChSerial;
    short       m_nChBatch;
    short       m_nChRetCode;
    short       m_nChRetMsg;
    short       m_nSysDate;
    short       m_nSysTime;
    short       m_nHoTxCode;
    short       m_nHoSerial;
    short       m_nHoRetCode;
    short       m_nHoRetMsg;
    short       m_nExTxCode;
    short       m_nExSerial;
    short       m_nExRetCode;
    short       m_nExRetMsg;
    short       m_nAuthNo;
    short       m_nRefNum;
    short       m_nSettleDate;
    short       m_nSettleTime;
    short       m_nTxTeller;
    short       m_nTxOrg;
    short       m_nErrHostId;
    short       m_nTxAmt;
    short       m_nAddAmt;
    short       m_nLateFee;
    short       m_nChkAmt;
    short       m_nTxNum;
    short       m_nChkNum;
    short       m_nTxIntegral;
    short       m_nChkIntegral;
    short       m_nStagingNum;
    short       m_nStagingCode;
    short       m_nReceiptBank;
    short       m_nIssureBank;
    short       m_nCupFlag;
    short       m_nPayerCardName;
    short       m_nPayerAcctType;
    short       m_nPayerAcct;
    short       m_nPayerBal;
    short       m_nPayerBalNum;
    short       m_nPayeeCardName;
    short       m_nPayeeAcctType;
    short       m_nPayeeAcct;
    short       m_nPayeeBal;
    short       m_nPayeeBalNum;
    short       m_nPeriod;
    short       m_nCustomerId;
    short       m_nOrderId;
    short       m_nChgDate;
    short       m_nChgTime;
    short       m_nAuthTeller;
    short       m_nChgTeller;
    short       m_nStatus;
    short       m_nAcctChkFlag;
    short       m_nOldStatus;
    short       m_nOldPtSerial;
    short       m_nOldPtDate;
    short       m_nMac;
    short       m_nNote;
    short       m_nDac;
}T_TxDetailInd;

typedef struct _tx_detail_exception
{
   char         m_sPtDate[9];
   int          m_nPtSerial;
   char         m_sPosTrace[11];
   char         m_sPosBatch[11];
   char         m_sTransDate[9];
   char         m_sTransTime[7];
   char         m_sAcctNo[33];
   char         m_sAcctNoType[2];
   double       m_fAmt;
   int          m_nNum;
   char         m_sMsgid[7];
   char         m_sProCode[7];
   char         m_sTerminalId[9];
   char         m_sMerchantId[16];
   char         m_sRefnum[13];
   char         m_sAuthNo[7];
   char         m_sCustomid[33];
   char         m_sIssCode[21];
   char         m_sAcqCode[21];
   char         m_sOldTrace[11];
   char         m_sResponse[11];
   char         m_sRetMsg[101];
   char         m_sSettleDate[9];
   char         m_sSysDate[9];
   char         m_sSysTime[7];
   char         m_sStatus[2];
   char         m_sChkFlag[2];
   char         m_sDac[17];
}T_TxDetailException;
typedef struct _tx_detail_exception_ind
{
   short        m_sPtDate;
   short        m_nPtSerial;
   short        m_sPosTrace;
   short        m_sPosBatch;
   short        m_sTransDate;
   short        m_sTransTime;
   short        m_sAcctNo;
   short        m_sAcctNoType;
   short        m_fAmt;
   short        m_nNum;
   short        m_sMsgid;
   short        m_sProCode;
   short        m_sTerminalId;
   short        m_sMerchantId;
   short        m_sRefnum;
   short        m_sAuthNo;
   short        m_sCustomid;
   short        m_sIssCode;
   short        m_sAcqCode;
   short        m_sOldTrace;
   short        m_sResponse;
   short        m_sRetMsg;
   short        m_sSettleDate;
   short        m_sSysDate;
   short        m_sSysTime;
   short        m_sStatus;
   short        m_sChkFlag;
   short        m_sDac;
}T_TxDetailExceptionInd;
 
/*终端参数结构*/
typedef struct  _terminal
{
  char m_sCode[9];
  char m_sMerchantCode[16];
  char m_sMasterKey[33];
  char m_sMasterKeyBak[33];
  char m_sMacKey[33];
  char m_sMacKeyC[33];
  char m_sPinKey[33];
  char m_sPinKeyC[33];
  int  m_nBatch;
  int  m_nSerial;
  int  m_nInvoice;
  char m_sSettleFlag[2];
  char m_sSettleDate[11];
  char m_sSettleNDate[11];
  char m_sLoginFlag[2];
  char m_sTeller[4];
  char m_sProId[21];
  char m_sProVer[21];
  char m_sDownPro[2];
  char m_sParamId[33];
  char m_sParamVer[21];
  char m_sDownParam[2];
  char m_sSetDate[11];
  char m_sSetTime[9];
  char m_sFacturer[4];
  char m_sHardModel[11];
  char m_sHardSerial[33];
  char m_sMenuId[33];
  char m_sMenuVer[21];
  char m_sDownMenu[2];
  char m_sTerminalType[3];
  char m_sNetId[21];
  char m_sNetOper[16];
  char m_sStatus[2];
  char m_sDac[17];
}T_Terminal;

typedef struct  _terminal_ind
{
  short m_nCode;
  short m_nMerchantCode;
  short m_nMasterKey;
  short m_nMasterKeyBak;
  short m_nMacKey;
  short m_nMacKeyC;
  short m_nPinKey;
  short m_nPinKeyC;
  short m_nBatch;
  short m_nSerial;
  short m_nInvoice;
  short m_nSettleFlag;
  short m_nSettleDate;
  short m_nSettleNDate;
  short m_nLoginFlag;
  short m_nTeller;
  short m_nProId;
  short m_nProVer;
  short m_nDownPro;
  short m_nParamId;
  short m_nParamVer;
  short m_nDownParam;
  short m_nSetDate;
  short m_nSetTime;
  short m_nFacturer;
  short m_nHardModel;
  short m_nHardSerial;
  short m_nMenuId;
  short m_nMenuVer;
  short m_nDownMenu;
  short m_nTerminalType;
  short m_nNetId;
  short m_nNetOper;
  short m_nStatus;
  short m_nDac;
}T_TerminalInd;

EXEC SQL END DECLARE SECTION;

#endif
